### ISSUE TITLE
Render undeformed renders the deformed outline

### ISSUE THREAD

**Issue by gateshian** [febiosoftware/FEBioStudio#24]
When displaying a model in a plot file, selecting "Render undeformed" renders the outline of the deformed geometry instead of the undeformed geometry.

Changing the Render mode does not stick, unless one first clicks on another option under Properties.

**Comment by SteveMaas1978** [comment]
The "render undeformed" option should work now.

The issue with the render mode was caused by the fact that the render mode (solid or wireframe) is handled differently, making this parameter obsolete. I removed the parameter. 

To toggle the render mode, you can use the menu View\Toggle Render Mode, or the context menu by right-clicking the Graphics View, or can use the "w" shortcut key.
