### ISSUE TITLE
Changing the Light direction has no effect

### ISSUE THREAD

**Issue by gateshian** [febiosoftware/FEBioStudio#27]
Changing the Light direction has no effect.
By default, the Light direction is displayed as (0,0,0), even though the code sets it to (1,1,1).

**Comment by SteveMaas1978** [comment]
This issue is fixed. Keep in mind that the light's position is with respect to "eye coordinates". The eye coordinates are always aligned with the screen, with x,y axes defined on the screen's plane, and the z axis coming out of the screen (toward the user). This is so that the scene will always be lit consistently, regardless of the actual position of the eye in global coordinates.

Also, the light is actually positioned at infinity, so the "position" is more like the direction in which the light is located. Or, the negative of the position is the direction in which the light shines. For instance, to create a "headlight", you would set the light's position to (0,0,1).
