### ISSUE TITLE
Crash on launch configuration + run on macOS Ventura / Apple M1

### ISSUE THREAD

**Issue by asrvsn** [febiosoftware/FEBioStudio#54]
Just wanted to report the following issue I'm encountering when attempting to run a model on a macOS Ventura / M1 pro system. The following occurs with both the current release build for macOS x86 and when built from source for arm64. 

Repro: 
* Run FEBio at the terminal using `FEBioStudio.app/Contents/MacOS/FEBioStudio`
* Create a model & add an analysis step per the tutorial
* Click `Run FEBIO`, notice there are no launch configurations present (unlike the tutorial, which suggests there should be a `Default`)
* Attempt to add a `local executable` launch configuration, the dialog is not populated, observe the following error:
```
2023-01-25 15:15:44.112 FEBioStudio[47704:20533739] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Item to remove does not belong to this menu
```
* Attempt to click `Run`, the app crashes with 
```
libc++abi: terminating with uncaught exception of type std::out_of_range: vector
zsh: abort      ./FEBioStudio -h
```
The last error, to me, suggests that the launch configuration list remaining empty is the issue. I'll post back if I can apply a fix for the launch config modal.

**Comment by asrvsn** [comment]
The workaround is to add at least two launch configurations initially, and the second one will persist. Still not sure why no `Default` launch configuration appears by default.

**Comment by SteveMaas1978** [comment]
Hi, thanks for reporting this issue. I'm not sure yet what is causing this, but can you try the following: start FEBio Studio from the terminal with the -reset command line option. For some users, this seems to fix it. Let us know what you find. 

Steve

**Comment by SteveMaas1978** [comment]
Glad to hear that fixed it! 

In the meantime, I did find the issue, and it looks like it only affects new users. The bug was that FEBioStudio expected there to be launch configurations defined in the settings file. But since there isn't any yet for first-time users, the launch configurations were not initialized, and the default configuration was not added. 

I pushed a dev update for Windows (to do a dev update, please see [here](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/)) and hopefully will get to the other OSs soon. 

Aside from adding the `-reset` flag on the command line, another workaround that should work, is by adding **two** custom launch configurations, then closing FEBioStudio and reopening it. The Default launch configuration should be available, and you can then delete the other launch configurations. 

I'm going to close this issue since it sounds like it's working for you now, but feel free to re-open if any problems remain. 

Steve
