### ISSUE TITLE
FEBio crashes upon attempt to run analysis. Solver not installing with Mac OS FEBio Studio installation?

### ISSUE THREAD

**Issue by Eric-Snively** [febiosoftware/FEBioStudio#63]
FEBioStudio is installed and can open models. When I attempt to run a tutorial model, the program crashes and closes instantly. When I attempt to find solvers in the Terminal (by typing febio3, instructed in "Installing FEBio Studio on macOS", it says "command not found."

When I go to Run FEBio,, launch configurations are empty and there are no FEBio executables.

Is  the solver not installing?

Thanks,
Eric

**Comment by michaelrossherron** [comment]
FEBio Studio is crashing due to trying to run the problem without any launch configurations. This is a bug, as there should always be a default launch configuration. This bug has been fixed, and the bugfix will be included in our 2.1 release happening in the next week or two. However, you can actually get this bugfix right now by updating FEBioStudio to the latest development version by following the instructions in [this link](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/#articleTOC_1).

Now that FEBio is on version 4, the command to run the solver is now _febio4_. I need to update the help article that you referenced. 

Let me know if you're still running into any issue. 

Michael Herron

**Comment by Eric-Snively** [comment]
Thanks, Michael and colleagues!

Eric

Eric Snively
Oklahoma State University
College of Osteopathic Medicine-Cherokee Nation
19500 E. Ross Street
Tahlequah, OK 74464
(740) 591 8928

Lab page: eric-snively-okstate.com

Facebook: bit.ly/2BPzWB7

OSU Anatomy and Vertebrate Paleontology Track:
https://medicine.okstate.edu/biomedical/paleontology/index.html
