### ISSUE TITLE
Showing the Load Controller associated with a Load in Model Viewer

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#77]
I am sharing an idea that I think is meaningful based on my user experience with FEBio.
Model viewer currently allows to visualise the properties of Loads in the Loads section, e.g. the step they are assign to, and the function defining the Load Controllers in their own section.
I think that it would be helpful to have a further Info in the Load property tab that specifies the Load Controller associated with that load (a sort of dropdown menu to check and potentially choose the Load Controller). As far as I know that can currently only be checked /modified through the Curve Editor, which is not a very intuitive approach in my opinion.
Thank you,
Luca

**Comment by SteveMaas1978** [comment]
Hi Luca,

In the latest development version I made a change where a graph icon is shown next to a load-controlled parameter (instead of a light green dot), and if you hover over it, a tooltip appears that will tell you which load controller is used by the parameter. I think this accomplishes your request, so please give that a try and let me know what you think. 
Thanks,
Steve

**Comment by modenaxe** [comment]
Hi Steve, 
I just tested it, very nice, I think this implements what I was asking for!
Thank you,
Luca
